services:
  - type: web
    name: voxel-arena
    runtime: static
    rootDir: blockshooter-master
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
